oanda:
  token: ''
  api:
    streaming_base: 'https://stream-fxpractice.oanda.com'
    rest_base:      'https://api-fxpractice.oanda.com'
    paths:
      rest: 
        account:    
          list:         '/v3/accounts'
          instruments:  '/v3/accounts/{}/instruments'
          price:        '/v3/accounts/{}/pricing'
      stream:
        account:
          price:        '/v3/accounts/{}/pricing/stream'

